#:kivy 2.1.0
<CollectionWindow>:
    TopMenuLayout:
        id: top_menu_layout

    RelativeLayout:
        size_hint: 1, 0.9
        pos_hint: {"x":0, "y":0}
        ScrollView:
            id: scroll_view
            do_scroll_x: False
            do_scroll_y: True
            bar_width: 0

            MyScrollViewLayout:
                id: my_sv_layout
                cols: 1
                height: self.minimum_height+root.label_height
                pos: root.pos
